apiVersion: apps/v1
kind: Deployment
metadata:
  name: khalims-brain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: khalims-brain
  template:
    metadata:
      labels:
        app: khalims-brain
    spec:
      containers:
      - name: khalims-brain
        image: khalims-brain:1.0.0
        imagePullPolicy: Never
