apiVersion: v1
kind: Service
metadata:
  name: khalims-brain-svc
  namespace: hdm
spec:
  type: NodePort
  ports:
  - port: 80           # Service 虚拟端口
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
  selector:
    app: khalims-brain
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: khalims-brain
  namespace: hdm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: khalims-brain
  template:
    metadata:
      labels:
        app: khalims-brain
    spec:
      containers:
      - name: khalims-brain
        image: hdm.io/khalims-brain:1.10.0
        imagePullPolicy: Never
        env:
        - name: KHALIMS_BRAIN_RABBITMQ_HOST
          value: "rabbitmq"
        - name: KHALIMS_BRAIN_PG_HOST
          value: "postgres-service"
        - name: KHALIMS_BRAIN_REDIS_HOST
          value: "redis-svc"
        - name: KHALIMS_BRAIN_ES_HOST
          value: "elasticsearch"
        - name: KHALIMS_BRAIN_RABBITMQ_PORT
          value: "5672"
        - name: KHALIMS_BRAIN_PG_PORT
          value: "5432"
        - name: KHALIMS_BRAIN_REDIS_PORT
          value: "6379"
        - name: KHALIMS_BRAIN_ES_PORT
          value: "9200"
        - name: KHALIMS_BRAIN_PG_DEFAULT_DB
          value: "postgres"
        - name: KHALIMS_BRAIN_PG_USER
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: username
        - name: KHALIMS_BRAIN_PG_PASSWD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: password
        - name: KHALIMS_BRAIN_RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_USER
        - name: KHALIMS_BRAIN_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_PASS
